"""
Install tab — Master App Catalog data.

2026-09-05 round-5 curation (user request: remove 18 named bloat/
duplicate/unwanted entries, add 6 replacements). IDs verified live
against winget/GitHub on 2026-09-05:
  * Removed (winget entries): CurseForge Launcher, Azahar, WeMod,
    PotPlayer, CapCut, Streamlabs, OP Auto Clicker, SignalRGB, NanaZip,
    PeaZip, Netflix, Hulu, Crunchyroll, Reddit, Pandora, SoundCloud,
    Tubi TV, Pluto TV, Vesktop (Vencord itself was never a separate
    catalog entry — only the Vesktop client existed).
  * Removed (manual-only): Pinokio, Reddit.
  * Added: LosslessCut, Microsoft PowerToys, Flameshot, MPC-HC
    (clsid2 fork), Blur-AutoClicker, Flycast — see per-entry comments
    below for winget-id adjudications and no-winget-package calls.
    BleachBit was already present (BleachBit.BleachBit) — not
    duplicated.
  * LosslessCut: mifi/lossless-cut has no OFFICIAL winget package
    (maintainer couldn't get the appx signed — winget-pkgs#72074).
    The only resolvable winget id is ch.LosslessCut, a third-party
    repack of mifi's own unmodified release binaries (verified live,
    v3.68.0). Kept as a winget entry since it installs mifi's real
    binaries, but the URL points at mifi's own site, not the repacker.
  * MPC-HC: the original mpc-hc.org project is unmaintained; clsid2/
    mpc-hc is the actively maintained continuation and is what
    `clsid2.mpc-hc` on winget actually ships (verified live, v2.7.4).
  * Flycast: NO winget package exists (confirmed against the
    flyinghead/flycast README — Android/Flatpak/Homebrew/Xbox only,
    no winget listed) -> manual entry, official builds page as the
    primary link, GitHub Releases as the fallback mirror.
  * Blur-AutoClicker / Flameshot / Microsoft PowerToys: all resolve
    on winget under Blur009.BlurAutoClicker, Flameshot.Flameshot,
    Microsoft.PowerToys respectively (all verified live).

2026-09-05 round-4 curation (user blueprint: bloatware purge + verified
replacements). IDs/URLs for every NEW or CHANGED entry were live-verified
via `winget search --exact` and HTTP probe on 2026-09-05; untouched
entries keep their previously verified state.

ID/URL adjudications (evidence-based, deviations from the blueprint's
stated IDs — the blueprint's literal IDs were tested first and FAILED):
  * Modrinth App: Modrinth.ModrinthApp resolves (v0.19.2) — as given.
  * Lime3DS: Lime3DS.Lime3DS does NOT resolve. The project merged into
    Azahar (lime3ds is archived); Azahar was winget's only 3DS emulator
    package at the time this note was written, but Azahar itself was
    REMOVED from the catalog in round-5 above per user request — the
    3DS slot is now the Lime3DS manual entry only.
    honest link-only, no fake
    installer ID (the same rule the catalog has always followed).
    https://lime3ds.github.io/ verified live (200).
  * BetterJoy: Davidobot.BetterJoy does NOT resolve on winget -> manual
    entry, GitHub releases verified live (200).
  * Raw Accel: no winget package; repo moved to RawAccelOfficial/rawaccel
    (blueprint's a1xd/rawaccel URL redirects there — verified live) ->
    manual entry with the FINAL redirect target as the URL.
  * AutoActions: Gistrec/AutoActions is 404 (repo gone); the live package
    is Codectory.AutoActions on winget (verified FOUND v1.9.27) ->
    winget entry with the project's current source.
  * Special K / Flawless Widescreen: both resolve on winget
    (SpecialK.SpecialK, FlawlessWidescreen.FlawlessWidescreen) ->
    promoted from the blueprint's manual list to real installer entries.
  * Mixxx: Mixxx.Mixxx resolves (v2.5.6) -> winget entry.
  * VoiceMeeter: VB-Audio.Voicemeeter resolves -> winget entry.
  * REAPER: Cockos.REAPER resolves (v7.79) -> winget entry.
  * Blockbench: JannisX11.Blockbench resolves (v5.1.6) -> winget entry.
  * Syncthing / Portmaster / Cryptomator / Espanso / Intel.PresentMon /
    Safing.Portmaster / henrypp simplewall: simplewall's real ID is
    Henry++.simplewall (henrypp.simplewall does not resolve); all others
    resolve as given.
  * Cinebench: blueprint says Maxon.Cinebench — does NOT resolve. Cinebench
    2024 remains the Store listing 9PGZKJC81Q7J (verified FOUND).
  * FurMark: blueprint says Geeks3D.FurMark — does NOT resolve; the real
    packages are Geeks3D.FurMark.1 (legacy) and Geeks3D.FurMark.2 (kept).
  * PotPlayer: RE-ADDED per blueprint, old daum.net domain is DEAD ->
    new official homepage https://potplayer.tv/ (verified live 200, and
    it is the URL winget's own package metadata publishes).
  * Amazon Games: Amazon.Games resolves (v3.0.9700.3) -> winget entry,
    not manual as sketched.
  * HoyoPlay: no winget package -> manual entry (URL verified live).
  * DaVinci Resolve: no winget package (Blackmagic ships its own
    installer) -> manual entry (URL verified live).
  * HeSuVi: SourceForge 403s scripted probes but is the project's own
    distribution point (SF policy: bot-block, domain intact) -> manual.
  * Blueprint Store IDs that do NOT resolve on the msstore source
    (9WZDNCNDDS8F Tubi, 9WZDNCRFJ37N Pluto TV, 9NV7WWL80C4F SoundCloud,
    9NBLGGH1Z42V Pandora, 9NBLGGH4XQ9X Reddit): kept as MANUAL link-only
    entries pointing at the services' own sites (verified by name search
    — none have a winget-installable Store package today).
  * Xbox Accessories: blueprint's 9NBLGGH30VJ3 is a TYPO for 9NBLGGH30XJ3
    (the live, previously verified ID) — kept 9NBLGGH30XJ3.
  * BlueStacks: REMOVED per user ruling 2026-09-05 (bloat: BlueStacks X,
    now.gg telemetry, boot ads). MuMu Player: REMOVED per the same ruling
    (proprietary NetEase telemetry). Clean replacement: Google Play Games
    for PC (manual, official Google client) + scrcpy (winget, FOSS phone
    mirroring — Genymobile.scrcpy verified FOUND v4.1; the ruling's
    'already available' premise did not hold, so it was added).
  * Riot Client: https://www.riotgames.com/ APPROVED per user ruling —
    the parent domain's unified client covers Valorant, LoL, TFT, 2XKO
    (playvalorant.com was single-game specific).
  * Unresolved Store IDs (Tubi, Pluto TV, SoundCloud, Pandora, Reddit):
    APPROVED as MANUAL_ONLY_APPS per user ruling — a dead Store ID would
    throw winget 0x80190194 at install time in the GUI; manual entries
    link the official sites instead. Streaming services placed in Media,
    Reddit kept in Utilities per the blueprint's category architecture.

Standing rules (unchanged):
  * winget install for every catalog app; MANUAL_ONLY_APPS are link-only.
  * "fallback_url": official/vendor page, project GitHub releases, or a
    mirror the project itself endorses. NEVER third-party aggregators.
  * A-Z within each category (validated on import).
"""

MSSTORE_IDS = {"9MVZQVXJBQ9V", "9N4D0MSMP0PT", "9MV0B5HZVK9Z", "9NZKPSTSNW4P",
               "9N5TDP8VCMHS", "XP8CLZL93F5Z4P", "9NBLGGH30XJ3",
               "9PGZKJC81Q7J"}

# Apps with NO winget package — shown in the catalog as manual-download
# links only (honest: we refuse to ship a fake installer entry).
MANUAL_ONLY_APPS = [
    {"id": 'manual:amd-auto-detect', "name": 'AMD Auto-Detect Installer', "category": 'Driver Installers & Hardware',
     "description": 'AMD installer is not on winget - opens the official AMD page', "foss": False,
     "url": 'https://www.amd.com/en/support/download/drivers.html'},
    {"id": 'manual:logitech-omm', "name": 'Logitech Onboard Memory Manager (OMM)', "category": 'Driver Installers & Hardware',
     "description": 'Official 5 MB portable utility to tune Logitech mouse DPI, binds, and polling without G HUB bloat', "foss": False,
     "url": 'https://support.logi.com/hc/en-us/articles/360059641133'},
    {"id": 'manual:sdio', "name": 'Snappy Driver Installer Origin', "category": 'Driver Installers & Hardware',
     "description": 'FOSS offline driver pack for PCs with no network drivers', "foss": True,
     "url": 'https://www.snappy-driver-installer.org/'},
    {"id": 'manual:hoyoplay', "name": 'HoyoPlay Launcher', "category": 'Game Launchers, Stores & Mod Managers',
     "description": 'HoYoverse launcher for Genshin Impact, Star Rail and ZZZ', "foss": False,
     "url": 'https://hoyoplay.hoyoverse.com/'},
    {"id": 'manual:riot-client', "name": 'Riot Client', "category": 'Game Launchers, Stores & Mod Managers',
     "description": 'Riot launcher for Valorant and League of Legends', "foss": False,
     "url": 'https://www.riotgames.com/'},
    {"id": 'manual:betterjoy', "name": 'BetterJoy', "category": 'Gaming Tools & Emulators',
     "description": 'Use Switch Pro controllers on PC with gyro support (no winget package — official releases on GitHub)', "foss": True,
     "url": 'https://github.com/Davidobot/BetterJoy/releases/latest'},
    {"id": 'manual:borderless-gaming', "name": 'Borderless Gaming', "category": 'Gaming Tools & Emulators',
     "description": 'Forces older games into borderless fullscreen mode', "foss": True,
     "url": 'https://github.com/andrewmd5/Borderless-Gaming/releases/latest'},
    {"id": 'manual:ds4windows', "name": 'DS4Windows', "category": 'Gaming Tools & Emulators',
     "description": 'Use PlayStation controllers on PC with gyro support', "foss": False,
     "url": 'https://github.com/Ryochan7/DS4Windows/releases/latest'},
    {"id": 'manual:google-play-games', "name": 'Google Play Games for PC', "category": 'Gaming Tools & Emulators',
     "description": 'Official Google Android gaming platform on PC with keyboard/mouse mapping and zero adware', "foss": False,
     "url": 'https://play.google.com/googleplaygames'},
    {"id": 'manual:lime3ds', "name": 'Lime3DS (3DS Emulator)', "category": 'Gaming Tools & Emulators',
     "description": 'Open-source Nintendo 3DS emulator with 4K upscaling (Citra continuation; no winget package — official releases on GitHub)', "foss": True,
     "url": 'https://lime3ds.github.io/', "fallback_url": 'https://github.com/Lime3DS/Lime3DS'},
    {"id": 'manual:raw-accel', "name": 'Raw Accel', "category": 'Gaming Tools & Emulators',
     "description": 'FOSS raw input mouse acceleration driver for fine-tuned aim curves', "foss": True,
     "url": 'https://github.com/RawAccelOfficial/rawaccel'},
    {"id": 'manual:flycast', "name": 'Flycast (Dreamcast/Naomi Emulator)', "category": 'Gaming Tools & Emulators',
     "description": 'Sega Dreamcast, Naomi and Atomiswave emulator (no winget package — official builds page)', "foss": True,
     "url": 'https://flyinghead.github.io/flycast-builds/', "fallback_url": 'https://github.com/flyinghead/flycast/releases'},
    {"id": 'manual:reshade', "name": 'ReShade', "category": 'Gaming Tools & Emulators',
     "description": 'Post-processing injector for custom graphics presets and screenshots', "foss": True,
     "url": 'https://reshade.me/'},
    {"id": 'manual:hesuvi', "name": 'HeSuVi', "category": 'Media, Streaming & Audio',
     "description": 'FOSS headphone virtualization surround (works with Equalizer APO)', "foss": True,
     "url": 'https://sourceforge.net/projects/hesuvi/'},
    {"id": 'manual:nvidia-broadcast', "name": 'NVIDIA Broadcast', "category": 'Media, Streaming & Audio',
     "description": 'AI mic noise removal and webcam effects (needs RTX)', "foss": False,
     "url": 'https://www.nvidia.com/en-us/geforce/broadcasting/broadcast-app/'},
    {"id": 'manual:touch-portal', "name": 'Touch Portal', "category": 'Media, Streaming & Audio',
     "description": 'Remote-control deck for OBS, stream macros and scenes', "foss": False,
     "url": 'https://www.touch-portal.com/'},
    {"id": 'manual:voicemeeter', "name": 'VB-Audio VoiceMeeter', "category": 'Media, Streaming & Audio',
     "description": 'Virtual audio mixer to route game, mic and Discord audio per-app', "foss": False,
     "url": 'https://vb-audio.com/Voicemeeter/'},
    {"id": 'manual:davinci-resolve', "name": 'DaVinci Resolve', "category": 'Creative & Productivity',
     "description": 'Hollywood-grade free video editor and color grading suite', "foss": False,
     "url": 'https://www.blackmagicdesign.com/products/davinciresolve'},
    {"id": 'manual:rustdesk', "name": 'RustDesk', "category": 'Utilities & Cleaners',
     "description": 'FOSS remote desktop - replaces TeamViewer', "foss": True,
     "url": 'https://rustdesk.com/', "fallback_url": 'https://github.com/rustdesk/rustdesk/releases/latest'},
    {"id": 'manual:winaero', "name": 'Winaero Tweaker', "category": 'Utilities & Cleaners',
     "description": 'Free all-in-one Windows tweaker, no ads or telemetry', "foss": False,
     "url": 'https://winaero.com/winaero-tweaker/'},
    {"id": 'manual:amuse-ai', "name": 'Amuse AI', "category": 'Local AI & GPU Model Runners',
     "description": 'Easy local AI image and video generator', "foss": False,
     "url": 'https://github.com/amuse-ai/amuse/releases/latest'},
    {"id": 'manual:fooocus', "name": 'Fooocus', "category": 'Local AI & GPU Model Runners',
     "description": 'Simple offline AI image generator, Midjourney-style', "foss": True,
     "url": 'https://github.com/lllyasviel/Fooocus/releases/latest'},
    {"id": 'manual:invokeai', "name": 'InvokeAI', "category": 'Local AI & GPU Model Runners',
     "description": 'Stable Diffusion studio with canvas and inpainting', "foss": True,
     "url": 'https://invoke.ai/', "fallback_url": 'https://github.com/invoke-ai/InvokeAI/releases/latest'},
    {"id": "manual:rpcs3", "name": "RPCS3", "category": "Gaming Tools & Emulators",
     "description": "PS3 emulator with 4K support - official build (no winget package)",
     "foss": True, "url": "https://rpcs3.net/"},
    {"id": "manual:anythingllm", "name": "AnythingLLM", "category": "Local AI & GPU Model Runners",
     "description": "Private AI chat with your PDFs and docs, offline (no winget package)",
     "foss": True, "url": "https://anythingllm.com/desktop"},
    {"id": "manual:stabilitymatrix", "name": "Stability Matrix", "category": "Local AI & GPU Model Runners",
     "description": "1-click manager for local AI image tools (no winget package)",
     "foss": True, "url": "https://lykos.ai/"},

]


APP_CATALOG = [
    # A. Driver Installers & Hardware
    {"id": 'Dell.CommandUpdate.Universal', "name": 'Dell / Alienware Command Update', "category": 'Driver Installers & Hardware',
     "description": 'Auto BIOS and driver updater for Dell/Alienware', "foss": False,
     "url": 'https://www.dell.com/support/'},
    {"id": 'Elgato.4KCaptureUtility', "name": 'Elgato 4K Capture Utility', "category": 'Driver Installers & Hardware',
     "description": 'Firmware updater for Elgato capture devices', "foss": False,
     "url": 'https://www.elgato.com/downloads'},
    {"id": 'seerge.g-helper', "name": 'G-Helper (ASUS ROG/TUF)', "category": 'Driver Installers & Hardware',
     "description": 'FOSS lightweight replacement for Armoury Crate', "foss": True,
     "url": 'https://github.com/seerge/g-helper'},
    {"id": 'Nefarius.HidHide', "name": 'HidHide (Controller Input Firewall)', "category": 'Driver Installers & Hardware',
     "description": 'Hides controllers to fix double-input bugs', "foss": True,
     "url": 'https://github.com/nefarius/HidHide'},
    {"id": 'Intel.IntelDriverAndSupportAssistant', "name": 'Intel Driver & Support Assistant', "category": 'Driver Installers & Hardware',
     "description": 'Auto-detects Intel CPUs, Arc/Iris GPUs, chipsets, Wi-Fi, and Bluetooth', "foss": False,
     "url": 'https://www.intel.com/content/www/us/en/support/detect.html'},
    {"id": 'BartoszCichecki.LenovoLegionToolkit', "name": 'Lenovo Legion Toolkit', "category": 'Driver Installers & Hardware',
     "description": 'FOSS Lenovo Legion driver and power manager', "foss": True,
     "url": 'https://github.com/BartoszCichecki/LenovoLegionToolkit'},
    {"id": 'Logitech.GHUB', "name": 'Logitech G HUB', "category": 'Driver Installers & Hardware',
     "description": 'Driver and firmware hub for Logitech gaming gear', "foss": False,
     "url": 'https://www.logitechg.com/innovation/g-hub.html'},
    {"id": 'XP8CLZL93F5Z4P', "name": 'NVIDIA App', "category": 'Driver Installers & Hardware',
     "description": 'GeForce driver installer with ShadowPlay', "foss": False,
     "url": 'https://www.nvidia.com/software/nvidia-app/'},
    {"id": 'ViGEm.ViGEmBus', "name": 'ViGEmBus (Virtual Gamepad Driver)', "category": 'Driver Installers & Hardware',
     "description": 'Virtual gamepad driver for controller mappers', "foss": True,
     "url": 'https://github.com/nefarius/ViGEmBus'},
    {"id": '9NBLGGH30XJ3', "name": 'Xbox Accessories', "category": 'Driver Installers & Hardware',
     "description": 'Calibrate and update firmware on Xbox controllers', "foss": False,
     "url": 'https://apps.microsoft.com/detail/9NBLGGH30XJ3'},
    # B. Game Launchers, Stores & Mod Managers
    {"id": 'Amazon.Games', "name": 'Amazon Games App', "category": 'Game Launchers, Stores & Mod Managers',
     "description": "Amazon's launcher for Prime Gaming freebies and its own titles", "foss": False,
     "url": 'https://gaming.amazon.com/'},
    {"id": 'Blizzard.BattleNet', "name": 'Battle.net', "category": 'Game Launchers, Stores & Mod Managers',
     "description": 'Blizzard launcher for Diablo, Overwatch, Call of Duty and WoW', "foss": False,
     "url": 'https://www.blizzard.com/'},
    {"id": 'ElectronicArts.EADesktop', "name": 'EA App', "category": 'Game Launchers, Stores & Mod Managers',
     "description": 'EA platform for Apex, Battlefield, EA Play', "foss": False,
     "url": 'https://www.ea.com/ea-app'},
    {"id": 'EpicGames.EpicGamesLauncher', "name": 'Epic Games Launcher', "category": 'Game Launchers, Stores & Mod Managers',
     "description": 'Required for Fortnite, Unreal Engine, and weekly free games', "foss": False,
     "url": 'https://store.epicgames.com/'},
    {"id": 'Nvidia.GeForceNow', "name": 'GeForce NOW', "category": 'Game Launchers, Stores & Mod Managers',
     "description": 'Stream RTX games to any device (cloud gaming)', "foss": False,
     "url": 'https://www.nvidia.com/geforce-now/'},
    {"id": 'GOG.Galaxy', "name": 'GOG Galaxy', "category": 'Game Launchers, Stores & Mod Managers',
     "description": 'DRM-free gaming platform and multi-store library aggregator', "foss": False,
     "url": 'https://www.gog.com/galaxy'},
    {"id": 'HeroicGamesLauncher.HeroicGamesLauncher', "name": 'Heroic Games Launcher', "category": 'Game Launchers, Stores & Mod Managers',
     "description": 'FOSS launcher for Epic Games, GOG, and Amazon Games', "foss": True,
     "url": 'https://heroicgameslauncher.com/'},
    {"id": 'ItchIo.Itch', "name": 'itch.io', "category": 'Game Launchers, Stores & Mod Managers',
     "description": 'Indie game marketplace client', "foss": True,
     "url": 'https://itch.io/app'},
    {"id": 'ModOrganizer2.modorganizer', "name": 'Mod Organizer 2', "category": 'Game Launchers, Stores & Mod Managers',
     "description": 'Best mod manager for Skyrim and Fallout', "foss": True,
     "url": 'https://modorganizer.org/'},
    {"id": 'Modrinth.ModrinthApp', "name": 'Modrinth App', "category": 'Game Launchers, Stores & Mod Managers',
     "description": 'Fast, modern, ad-free open-source Minecraft launcher with built-in mods and shaders', "foss": True,
     "url": 'https://modrinth.com/app', "fallback_url": 'https://github.com/modrinth/theseus'},
    {"id": 'Playnite.Playnite', "name": 'Playnite', "category": 'Game Launchers, Stores & Mod Managers',
     "description": 'Unified FOSS game library manager with full emulator and store integration', "foss": True,
     "url": 'https://playnite.link/'},
    {"id": 'PrismLauncher.PrismLauncher', "name": 'Prism Launcher', "category": 'Game Launchers, Stores & Mod Managers',
     "description": 'FOSS Minecraft launcher with multi-instance and modpack management', "foss": True,
     "url": 'https://prismlauncher.org/'},
    {"id": 'ebkr.r2modman', "name": 'r2modman', "category": 'Game Launchers, Stores & Mod Managers',
     "description": 'Clean FOSS Thunderstore mod manager for Lethal Company, Valheim, and RoR2', "foss": True,
     "url": 'https://thunderstore.io/package/ebkr/r2modman/'},
    {"id": 'Roblox.Roblox', "name": 'Roblox Player', "category": 'Game Launchers, Stores & Mod Managers',
     "description": 'Official desktop client for Roblox games', "foss": False,
     "url": 'https://www.roblox.com/'},
    {"id": 'RockstarGames.Launcher', "name": 'Rockstar Games Launcher', "category": 'Game Launchers, Stores & Mod Managers',
     "description": 'PC launcher for GTA and Red Dead games', "foss": False,
     "url": 'https://www.rockstargames.com/'},
    {"id": 'Valve.Steam', "name": 'Steam', "category": 'Game Launchers, Stores & Mod Managers',
     "description": 'The primary digital PC gaming storefront and community', "foss": False,
     "url": 'https://store.steampowered.com/'},
    {"id": 'Ubisoft.Connect', "name": 'Ubisoft Connect', "category": 'Game Launchers, Stores & Mod Managers',
     "description": "Ubisoft's launcher for Assassin's Creed, Far Cry and Rainbow Six", "foss": False,
     "url": 'https://ubisoftconnect.com/'},
    {"id": 'NexusMods.Vortex', "name": 'Vortex Mod Manager', "category": 'Game Launchers, Stores & Mod Managers',
     "description": 'Nexus mod manager for Cyberpunk, BG3 and more', "foss": True,
     "url": 'https://www.nexusmods.com/about/vortex/'},
    # C. Gaming Tools & Emulators
    {"id": 'AntiMicroX.antimicrox', "name": 'AntiMicroX', "category": 'Gaming Tools & Emulators',
     "description": 'Maps controller inputs to keyboard/mouse with virtual gamepad emulation', "foss": True,
     "url": 'https://github.com/AntiMicroX/antimicrox'},
    {"id": 'Codectory.AutoActions', "name": 'AutoActions', "category": 'Gaming Tools & Emulators',
     "description": 'FOSS utility to auto-switch Windows power plans and audio devices per game', "foss": True,
     "url": 'https://github.com/Codectory/AutoActions'},
    {"id": 'Cemu.Cemu', "name": 'Cemu (Wii U Emulator)', "category": 'Gaming Tools & Emulators',
     "description": 'Wii U emulator (plays Zelda: Breath of the Wild at 4K/60+ FPS)', "foss": True,
     "url": 'https://cemu.info/'},
    {"id": 'StreetPea.chiaki-ng', "name": 'chiaki-ng (PS Remote Play)', "category": 'Gaming Tools & Emulators',
     "description": 'FOSS PS4/PS5 remote play client — low latency, any controller', "foss": True,
     "url": 'https://github.com/streetpea/chiaki-ng'},
    {"id": 'DolphinEmulator.Dolphin', "name": 'Dolphin Emulator', "category": 'Gaming Tools & Emulators',
     "description": 'GameCube & Wii emulator with 4K resolution upscaling and texture packs', "foss": True,
     "url": 'https://dolphin-emu.org/'},
    {"id": 'Stenzek.DuckStation', "name": 'DuckStation', "category": 'Gaming Tools & Emulators',
     "description": 'PlayStation 1 emulator featuring PGXP geometry correction and widescreen', "foss": True,
     "url": 'https://github.com/stenzek/duckstation'},
    {"id": 'FlawlessWidescreen.FlawlessWidescreen', "name": 'Flawless Widescreen', "category": 'Gaming Tools & Emulators',
     "description": 'Fixes HUD and FOV for ultrawide monitors in hundreds of games', "foss": False,
     "url": 'https://www.flawlesswidescreen.org/'},
    {"id": 'mtkennerly.ludusavi', "name": 'Ludusavi (Game Save Backup)', "category": 'Gaming Tools & Emulators',
     "description": 'Auto backup for 10,000+ PC game saves', "foss": True,
     "url": 'https://github.com/mtkennerly/ludusavi'},
    {"id": 'Blinue.Magpie', "name": 'Magpie (FSR Upscaler)', "category": 'Gaming Tools & Emulators',
     "description": 'Adds FSR, integer scaling, and Lanczos upscaling to any windowed game', "foss": True,
     "url": 'https://github.com/Blinue/Magpie'},
    {"id": 'melonDS.melonDS', "name": 'melonDS (Nintendo DS Emulator)', "category": 'Gaming Tools & Emulators',
     "description": 'Fast Nintendo DS emulator with 3D upscaling', "foss": True,
     "url": 'https://melonds.kuribo64.net/'},
    {"id": 'JeffreyPfau.mGBA', "name": 'mGBA', "category": 'Gaming Tools & Emulators',
     "description": 'Fast, highly accurate Game Boy Advance / Color emulator with rewinding', "foss": True,
     "url": 'https://mgba.io/'},
    {"id": 'MoonlightGameStreamingProject.Moonlight', "name": 'Moonlight Game Streaming', "category": 'Gaming Tools & Emulators',
     "description": 'FOSS client to stream PC games to laptops, TVs, or Steam Deck at 120 FPS', "foss": True,
     "url": 'https://moonlight-stream.org/'},
    {"id": 'Parsec.Parsec', "name": 'Parsec', "category": 'Gaming Tools & Emulators',
     "description": 'Low-latency remote play for split-screen games', "foss": False,
     "url": 'https://parsec.app/'},
    {"id": 'PCSX2Team.PCSX2', "name": 'PCSX2', "category": 'Gaming Tools & Emulators',
     "description": 'PlayStation 2 emulator with widescreen patches and HD rendering', "foss": True,
     "url": 'https://pcsx2.net/'},
    {"id": 'PPSSPPTeam.PPSSPP', "name": 'PPSSPP', "category": 'Gaming Tools & Emulators',
     "description": 'PlayStation Portable emulator with HD resolution and texture upscaling', "foss": True,
     "url": 'https://www.ppsspp.org/'},
    {"id": 'Libretro.RetroArch', "name": 'RetroArch', "category": 'Gaming Tools & Emulators',
     "description": 'All-in-one frontend for retro consoles', "foss": True,
     "url": 'https://www.retroarch.com/'},
    {"id": 'Genymobile.scrcpy', "name": 'scrcpy', "category": 'Gaming Tools & Emulators',
     "description": 'FOSS mirror and control your Android phone from PC with near-zero lag and zero ads', "foss": True,
     "url": 'https://github.com/Genymobile/scrcpy'},
    {"id": 'SpecialK.SpecialK', "name": 'Special K', "category": 'Gaming Tools & Emulators',
     "description": 'Comprehensive game modding framework: HDR, FPS unlock, cache fixes', "foss": False,
     "url": 'https://www.special-k.info/'},
    {"id": 'SteamGridDB.RomManager', "name": 'Steam ROM Manager', "category": 'Gaming Tools & Emulators',
     "description": 'Adds retro games to Steam with art', "foss": True,
     "url": 'https://github.com/SteamGridDB/steam-rom-manager'},
    {"id": 'LizardByte.Sunshine', "name": 'Sunshine Game Server', "category": 'Gaming Tools & Emulators',
     "description": 'FOSS self-hosted game stream server for Moonlight', "foss": True,
     "url": 'https://github.com/LizardByte/Sunshine'},
    {"id": 'xemu-project.xemu', "name": 'xemu (Original Xbox Emulator)', "category": 'Gaming Tools & Emulators',
     "description": 'Original Xbox emulator with higher resolutions', "foss": True,
     "url": 'https://xemu.app/'},
    {"id": 'Xenia.Xenia', "name": 'xenia (Xbox 360 Emulator)', "category": 'Gaming Tools & Emulators',
     "description": 'Xbox 360 emulator (RDR1, Halo 3 at 60 FPS)', "foss": True,
     "url": 'https://xenia.jp/'},
    # D. Web Browsers
    {"id": 'Brave.Brave', "name": 'Brave Browser', "category": 'Web Browsers',
     "description": 'Chromium-based browser with built-in ad/tracker blocking and low RAM usage', "foss": True,
     "url": 'https://brave.com/'},
    {"id": 'DuckDuckGo.DesktopBrowser', "name": 'DuckDuckGo Privacy Browser', "category": 'Web Browsers',
     "description": 'Private browser with tracker blocking', "foss": True,
     "url": 'https://duckduckgo.com/windows'},
    {"id": 'Google.Chrome', "name": 'Google Chrome', "category": 'Web Browsers',
     "description": 'Standard Chromium browser for Google account syncing and ecosystem tools', "foss": False,
     "url": 'https://www.google.com/chrome/'},
    {"id": 'LibreWolf.LibreWolf', "name": 'LibreWolf', "category": 'Web Browsers',
     "description": 'Privacy-hardened Firefox with telemetry stripped and uBlock Origin included', "foss": True,
     "url": 'https://librewolf.net/'},
    {"id": 'Mozilla.Firefox', "name": 'Mozilla Firefox', "category": 'Web Browsers',
     "description": 'Independent open-source browser with rich privacy and extension support', "foss": True,
     "url": 'https://www.mozilla.org/firefox/'},
    {"id": 'TorProject.TorBrowser', "name": 'Tor Browser', "category": 'Web Browsers',
     "description": 'Maximum anonymity via the Tor network', "foss": True,
     "url": 'https://www.torproject.org/'},
    {"id": 'Zen-Team.Zen-Browser', "name": 'Zen Browser', "category": 'Web Browsers',
     "description": 'High-speed modern Firefox fork with native vertical tabs and split view', "foss": True,
     "url": 'https://zen-browser.app/'},
    # E. Media, Streaming & Audio
    {"id": 'AIMP.AIMP', "name": 'AIMP', "category": 'Media, Streaming & Audio',
     "description": 'Music player with equalizer and internet radio', "foss": False,
     "url": 'https://www.aimp.ru/'},
    {"id": 'Audacity.Audacity', "name": 'Audacity', "category": 'Media, Streaming & Audio',
     "description": 'Multi-track audio recorder, editor, and mic noise remover', "foss": True,
     "url": 'https://www.audacityteam.org/'},
    {"id": 'ChatterinoTeam.Chatterino', "name": 'Chatterino', "category": 'Media, Streaming & Audio',
     "description": 'Lightweight Twitch chat with 7TV/BTTV emotes', "foss": True,
     "url": 'https://chatterino.com/'},
    {"id": 'Discord.Discord', "name": 'Discord', "category": 'Media, Streaming & Audio',
     "description": 'Standard gaming voice, chat, and community platform', "foss": False,
     "url": 'https://discord.com/'},
    {"id": 'Digimezzo.Dopamine.3', "name": 'Dopamine', "category": 'Media, Streaming & Audio',
     "description": 'Clean minimalist local music player', "foss": True,
     "url": 'https://github.com/digimezzo/dopamine-windows/releases/latest'},
    {"id": 'File-New-Project.EarTrumpet', "name": 'EarTrumpet', "category": 'Media, Streaming & Audio',
     "description": 'Per-app volume mixer for games and Discord', "foss": True,
     "url": 'https://eartrumpet.app/'},
    {"id": 'FreeTube.FreeTube', "name": 'FreeTube', "category": 'Media, Streaming & Audio',
     "description": 'Private ad-free YouTube client with SponsorBlock and local subscriptions', "foss": True,
     "url": 'https://freetubeapp.io/'},
    {"id": 'FxSound.FxSound', "name": 'FxSound', "category": 'Media, Streaming & Audio',
     "description": 'Real-time audio booster and equalizer — hear footsteps clearly in FPS games', "foss": True,
     "url": 'https://www.fxsound.com/'},
    {"id": 'HandBrake.HandBrake', "name": 'HandBrake', "category": 'Media, Streaming & Audio',
     "description": 'GPU-accelerated video compressor and clip transcoder', "foss": True,
     "url": 'https://handbrake.fr/'},
    {"id": 'Jellyfin.JellyfinMediaPlayer', "name": 'Jellyfin Media Player', "category": 'Media, Streaming & Audio',
     "description": 'Desktop PLAYER app for watching your Jellyfin server on PC (pair with Jellyfin Server)', "foss": True,
     "url": 'https://github.com/jellyfin/jellyfin-media-player/releases/latest'},
    {"id": 'Jellyfin.Server', "name": 'Jellyfin Server', "category": 'Media, Streaming & Audio',
     "description": 'Free private media SERVER for movies and music (pair with Jellyfin Media Player)', "foss": True,
     "url": 'https://jellyfin.org/downloads/server/', "fallback_url": 'https://repo.jellyfin.org/'},
    {"id": 'XBMCFoundation.Kodi', "name": 'Kodi', "category": 'Media, Streaming & Audio',
     "description": 'FOSS home theater and media center hub', "foss": True,
     "url": 'https://kodi.tv/'},
    {"id": 'ch.LosslessCut', "name": 'LosslessCut', "category": 'Media, Streaming & Audio',
     "description": 'FOSS Swiss-army-knife video/audio trimmer — cuts and joins without re-encoding', "foss": True,
     "url": 'https://mifi.no/losslesscut/', "fallback_url": 'https://github.com/mifi/lossless-cut/releases/latest'},
    {"id": 'MediaArea.MediaInfo.GUI', "name": 'MediaInfo', "category": 'Media, Streaming & Audio',
     "description": 'Shows codecs and specs inside any video file', "foss": True,
     "url": 'https://mediaarea.net/MediaInfo'},
    {"id": 'Mixxx.Mixxx', "name": 'Mixxx DJ Software', "category": 'Media, Streaming & Audio',
     "description": 'FOSS DJ mixer with vinyl control, streaming and recording', "foss": True,
     "url": 'https://mixxx.org/'},
    {"id": 'MoritzBunkus.MKVToolNix', "name": 'MKVToolNix', "category": 'Media, Streaming & Audio',
     "description": 'FOSS toolkit to edit MKV video files', "foss": True,
     "url": 'https://mkvtoolnix.download/'},
    {"id": 'FlorianHeidenreich.Mp3tag', "name": 'Mp3tag', "category": 'Media, Streaming & Audio',
     "description": 'Batch metadata and cover-art editor for audio libraries', "foss": False,
     "url": 'https://www.mp3tag.de/en/'},
    {"id": 'clsid2.mpc-hc', "name": 'MPC-HC', "category": 'Media, Streaming & Audio',
     "description": 'Hardware-accelerated media player — maintained community fork of Media Player Classic', "foss": True,
     "url": 'https://github.com/clsid2/mpc-hc'},
    {"id": 'Mumble.Mumble.Client', "name": 'Mumble', "category": 'Media, Streaming & Audio',
     "description": 'FOSS low-latency positional voice chat for teams (TeamSpeak alternative)', "foss": True,
     "url": 'https://www.mumble.info/downloads/', "fallback_url": 'https://github.com/mumble-voip/mumble/releases/latest'},
    {"id": 'MusicBrainz.Picard', "name": 'MusicBrainz Picard', "category": 'Media, Streaming & Audio',
     "description": 'Auto-tagger that fingerprints songs to fix missing tags and album artwork', "foss": True,
     "url": 'https://picard.musicbrainz.org/'},
    {"id": 'OBSProject.OBSStudio', "name": 'OBS Studio', "category": 'Media, Streaming & Audio',
     "description": 'Open-source live streaming, screen recording, and broadcasting software', "foss": True,
     "url": 'https://obsproject.com/'},
    {"id": 'Plex.PlexHTPC', "name": 'Plex HTPC (Player)', "category": 'Media, Streaming & Audio',
     "description": 'Big-screen Plex PLAYER for TVs and controllers (pair with Plex Media Server)', "foss": False,
     "url": 'https://www.plex.tv/media-server-downloads/#plex-apps'},
    {"id": 'Plex.PlexMediaServer', "name": 'Plex Media Server', "category": 'Media, Streaming & Audio',
     "description": 'Organizes your personal media libraries and streams them to any device (the SERVER)', "foss": False,
     "url": 'https://www.plex.tv/media-server-downloads/#plex-media-server'},
    {"id": 'Spotify.Spotify', "name": 'Spotify', "category": 'Media, Streaming & Audio',
     "description": 'Desktop music and podcast streaming client', "foss": False,
     "url": 'https://www.spotify.com/'},
    {"id": 'KRTirtho.Spotube', "name": 'Spotube', "category": 'Media, Streaming & Audio',
     "description": 'Spotify client that plays and downloads tracks as MP3/FLAC', "foss": True,
     "url": 'https://spotube.cc/'},
    {"id": 'Stremio.Stremio', "name": 'Stremio', "category": 'Media, Streaming & Audio',
     "description": 'All-in-one media aggregator for videos, series, and channels', "foss": True,
     "url": 'https://www.stremio.com/'},
    {"id": 'Nikse.SubtitleEdit', "name": 'Subtitle Edit', "category": 'Media, Streaming & Audio',
     "description": 'FOSS subtitle editor and synchronizer', "foss": True,
     "url": 'https://www.nikse.dk/subtitleedit'},
    {"id": 'TeamSpeakSystems.TeamSpeakClient', "name": 'TeamSpeak 3', "category": 'Media, Streaming & Audio',
     "description": 'Low-latency tactical voice chat for sim-racing, ARMA, and competitive teams', "foss": False,
     "url": 'https://www.teamspeak.com/'},
    {"id": 'VideoLAN.VLC', "name": 'VLC Media Player', "category": 'Media, Streaming & Audio',
     "description": 'Versatile open-source media player supporting all audio and video formats', "foss": True,
     "url": 'https://www.videolan.org/vlc/'},
    {"id": 'dsymbol.yt-dlp-gui', "name": 'yt-dlp-gui', "category": 'Media, Streaming & Audio',
     "description": 'Lightweight, cross-platform graphical PySide6/Qt interface for yt-dlp', "foss": True,
     "url": 'https://github.com/dsymbol/yt-dlp-gui'},
    # F. Creative & Productivity
    {"id": 'BlenderFoundation.Blender', "name": 'Blender', "category": 'Creative & Productivity',
     "description": 'Professional 3D modeling, animation, VFX, and game asset creation suite', "foss": True,
     "url": 'https://www.blender.org/'},
    {"id": 'JannisX11.Blockbench', "name": 'Blockbench', "category": 'Creative & Productivity',
     "description": 'FOSS low-poly 3D model editor for Minecraft and game assets', "foss": True,
     "url": 'https://www.blockbench.net/'},
    {"id": 'calibre.calibre', "name": 'Calibre', "category": 'Creative & Productivity',
     "description": 'The premier open-source e-book manager, converter, and reader suite', "foss": True,
     "url": 'https://calibre-ebook.com/'},
    {"id": 'DevToys-app.DevToys', "name": 'DevToys', "category": 'Creative & Productivity',
     "description": 'Offline dev toolkit: JSON, regex, converters', "foss": True,
     "url": 'https://devtoys.app/'},
    {"id": 'Docker.DockerDesktop', "name": 'Docker Desktop', "category": 'Creative & Productivity',
     "description": 'Run containerized apps locally', "foss": False,
     "url": 'https://www.docker.com/'},
    {"id": 'GIMP.GIMP', "name": 'GIMP', "category": 'Creative & Productivity',
     "description": 'Open-source image editor', "foss": True,
     "url": 'https://www.gimp.org/'},
    {"id": 'Git.Git', "name": 'Git', "category": 'Creative & Productivity',
     "description": 'The universal standard distributed version control system for source code', "foss": True,
     "url": 'https://git-scm.com/'},
    {"id": 'GitHub.GitHubDesktop', "name": 'GitHub Desktop', "category": 'Creative & Productivity',
     "description": 'Simple graphical client for Git and GitHub', "foss": True,
     "url": 'https://desktop.github.com/'},
    {"id": 'GodotEngine.GodotEngine', "name": 'Godot Engine', "category": 'Creative & Productivity',
     "description": 'Lightweight, beginner-friendly 2D/3D open-source game development engine', "foss": True,
     "url": 'https://godotengine.org/'},
    {"id": 'Inkscape.Inkscape', "name": 'Inkscape', "category": 'Creative & Productivity',
     "description": 'FOSS vector graphics editor (Illustrator alternative)', "foss": True,
     "url": 'https://inkscape.org/'},
    {"id": 'IrfanSkiljan.IrfanView', "name": 'IrfanView', "category": 'Creative & Productivity',
     "description": 'Ultra-fast, lightweight classic graphic viewer with batch conversion tools', "foss": False,
     "url": 'https://www.irfanview.com/'},
    {"id": 'KDE.Kdenlive', "name": 'Kdenlive', "category": 'Creative & Productivity',
     "description": 'Full FOSS video editor for game montages and YouTube (Premiere alternative)', "foss": True,
     "url": 'https://kdenlive.org/'},
    {"id": 'KDE.Krita', "name": 'Krita', "category": 'Creative & Productivity',
     "description": 'Professional FOSS digital painting, sketching, and concept art studio', "foss": True,
     "url": 'https://krita.org/'},
    {"id": 'TheDocumentFoundation.LibreOffice', "name": 'LibreOffice', "category": 'Creative & Productivity',
     "description": 'Complete open-source office suite', "foss": True,
     "url": 'https://www.libreoffice.org/'},
    {"id": 'OpenJS.NodeJS.LTS', "name": 'Node.js (LTS)', "category": 'Creative & Productivity',
     "description": 'JavaScript runtime for web development', "foss": True,
     "url": 'https://nodejs.org/'},
    {"id": 'Notepad++.Notepad++', "name": 'Notepad++', "category": 'Creative & Productivity',
     "description": 'Fast, tabbed text editor for tweaking game configs (.ini/.json) and code', "foss": True,
     "url": 'https://notepad-plus-plus.org/'},
    {"id": 'Obsidian.Obsidian', "name": 'Obsidian', "category": 'Creative & Productivity',
     "description": 'Private local Markdown notes with graph view', "foss": False,
     "url": 'https://obsidian.md/'},
    {"id": 'ONLYOFFICE.DesktopEditors', "name": 'ONLYOFFICE Desktop Editors', "category": 'Creative & Productivity',
     "description": 'FOSS office suite with true MS Office fidelity', "foss": True,
     "url": 'https://www.onlyoffice.com/'},
    {"id": 'dotPDN.PaintDotNet', "name": 'Paint.NET', "category": 'Creative & Productivity',
     "description": 'Fast, layer-based image and photo editor for Windows', "foss": False,
     "url": 'https://www.getpaint.net/'},
    {"id": 'geeksoftwareGmbH.PDF24Creator', "name": 'PDF24 Creator', "category": 'Creative & Productivity',
     "description": 'Free offline toolbox to merge, split, compress, and edit PDF documents', "foss": False,
     "url": 'https://www.pdf24.org/'},
    {"id": 'Proton.ProtonMail', "name": 'Proton Mail Desktop', "category": 'Creative & Productivity',
     "description": 'Encrypted Proton Mail desktop app', "foss": True,
     "url": 'https://proton.me/mail'},
    {"id": 'Python.Python.3.12', "name": 'Python 3.12', "category": 'Creative & Productivity',
     "description": 'Runtime for AI, automation and scripting', "foss": True,
     "url": 'https://www.python.org/'},
    {"id": 'jurplel.qView', "name": 'qView', "category": 'Creative & Productivity',
     "description": 'Ultra-minimal fast image viewer', "foss": True,
     "url": 'https://interversehq.com/qview/'},
    {"id": 'Cockos.REAPER', "name": 'REAPER', "category": 'Creative & Productivity',
     "description": 'Lightweight pro DAW with 60-day full eval — great for game audio and voiceover', "foss": False,
     "url": 'https://www.reaper.fm/'},
    {"id": 'NickeManarin.ScreenToGif', "name": 'ScreenToGif', "category": 'Creative & Productivity',
     "description": 'FOSS screen recorder with GIF editor', "foss": True,
     "url": 'https://www.screentogif.com/'},
    {"id": 'SumatraPDF.SumatraPDF', "name": 'SumatraPDF', "category": 'Creative & Productivity',
     "description": 'Ultra-fast, lightweight open-source PDF, EPUB, MOBI, and comic reader', "foss": True,
     "url": 'https://www.sumatrapdfreader.org/'},
    {"id": 'VSCodium.VSCodium', "name": 'VSCodium', "category": 'Creative & Productivity',
     "description": 'VS Code without telemetry or tracking', "foss": True,
     "url": 'https://vscodium.com/'},
    # G. Utilities & Cleaners
    {"id": '7zip.7zip', "name": '7-Zip', "category": 'Utilities & Cleaners',
     "description": 'High-compression archiver (ZIP, 7Z, RAR, TAR)', "foss": True,
     "url": 'https://www.7-zip.org/'},
    {"id": 'amir1376.ABDownloadManager', "name": 'AB Download Manager', "category": 'Utilities & Cleaners',
     "description": 'Fast multi-threaded download accelerator', "foss": True,
     "url": 'https://abdownloadmanager.com/'},
    {"id": 'HulubuluSoftware.AdvancedRenamer', "name": 'Advanced Renamer', "category": 'Utilities & Cleaners',
     "description": 'Batch-renames files and mod folders with rules', "foss": False,
     "url": 'https://www.advancedrenamer.com/'},
    {"id": 'Malwarebytes.AdwCleaner', "name": 'AdwCleaner', "category": 'Utilities & Cleaners',
     "description": 'Free adware and junkware remover', "foss": False,
     "url": 'https://www.malwarebytes.com/adwcleaner'},
    {"id": 'AltSnap.AltSnap', "name": 'AltSnap', "category": 'Utilities & Cleaners',
     "description": 'Move and resize windows with Alt+drag', "foss": True,
     "url": 'https://github.com/RamonUnch/AltSnap'},
    {"id": 'AutoHotkey.AutoHotkey', "name": 'AutoHotkey', "category": 'Utilities & Cleaners',
     "description": 'Open-source macro and scripting engine for game keybinds and automation', "foss": True,
     "url": 'https://www.autohotkey.com/'},
    {"id": 'BleachBit.BleachBit', "name": 'BleachBit', "category": 'Utilities & Cleaners',
     "description": 'FOSS deep disk cleaner and privacy scrubber', "foss": True,
     "url": 'https://www.bleachbit.org/'},
    {"id": 'Blur009.BlurAutoClicker', "name": 'Blur-AutoClicker', "category": 'Utilities & Cleaners',
     "description": 'FOSS accuracy-focused auto-clicker with hotkeys and CPS ranges', "foss": True,
     "url": 'https://github.com/Blur009/Blur-AutoClicker'},
    {"id": 'Klocman.BulkCrapUninstaller', "name": 'Bulk Crap Uninstaller (BCU)', "category": 'Utilities & Cleaners',
     "description": 'Batch uninstaller that cleans leftover files', "foss": True,
     "url": 'https://www.bcuninstaller.com/'},
    {"id": 'Cloudflare.Warp', "name": 'Cloudflare WARP (1.1.1.1)', "category": 'Utilities & Cleaners',
     "description": 'Fast free encrypted tunnel for safer browsing', "foss": False,
     "url": 'https://one.one.one.one/'},
    {"id": 'Cryptomator.Cryptomator', "name": 'Cryptomator', "category": 'Utilities & Cleaners',
     "description": 'FOSS per-file encryption for cloud drives — mod vaults stay private', "foss": True,
     "url": 'https://cryptomator.org/'},
    {"id": 'qarmin.czkawka.gui', "name": 'Czkawka', "category": 'Utilities & Cleaners',
     "description": 'Fast Rust duplicate file and image cleaner', "foss": True,
     "url": 'https://github.com/qarmin/czkawka'},
    {"id": 'Espanso.Espanso', "name": 'Espanso', "category": 'Utilities & Cleaners',
     "description": 'FOSS text expander — type short snippets that unfold into full text', "foss": True,
     "url": 'https://espanso.org/'},
    {"id": 'voidtools.Everything', "name": 'Everything Search', "category": 'Utilities & Cleaners',
     "description": 'Locates any file or folder across your entire PC in milliseconds', "foss": False,
     "url": 'https://www.voidtools.com/'},
    {"id": 'FastCopy.FastCopy', "name": 'FastCopy', "category": 'Utilities & Cleaners',
     "description": 'The fastest file copy, backup, and transfer utility on Windows', "foss": True,
     "url": 'https://fastcopy.jp/'},
    {"id": 'Flameshot.Flameshot', "name": 'Flameshot', "category": 'Utilities & Cleaners',
     "description": 'FOSS screenshot tool with in-app annotation and instant upload', "foss": True,
     "url": 'https://flameshot.org/'},
    {"id": 'Flow-Launcher.Flow-Launcher', "name": 'Flow Launcher', "category": 'Utilities & Cleaners',
     "description": 'Alt+Space launcher for files, games and math', "foss": True,
     "url": 'https://www.flowlauncher.com/'},
    {"id": 'KeePassXCTeam.KeePassXC', "name": 'KeePassXC', "category": 'Utilities & Cleaners',
     "description": 'FOSS offline password manager for game and app logins', "foss": True,
     "url": 'https://keepassxc.org/'},
    {"id": 'Tyrrrz.LightBulb', "name": 'LightBulb', "category": 'Utilities & Cleaners',
     "description": 'Blue light filter — lighter than f.lux', "foss": True,
     "url": 'https://github.com/Tyrrrz/LightBulb'},
    {"id": 'rocksdanister.LivelyWallpaper', "name": 'Lively Wallpaper', "category": 'Utilities & Cleaners',
     "description": 'Free FOSS animated wallpaper engine (auto-pauses while gaming)', "foss": True,
     "url": 'https://www.rocksdanister.com/lively/'},
    {"id": 'LocalSend.LocalSend', "name": 'LocalSend', "category": 'Utilities & Cleaners',
     "description": 'FOSS AirDrop alternative for PC and phones', "foss": True,
     "url": 'https://localsend.org/'},
    {"id": 'Malwarebytes.Malwarebytes', "name": 'Malwarebytes Free', "category": 'Utilities & Cleaners',
     "description": 'Free on-demand virus scanner (shows Premium upsells)', "foss": False,
     "url": 'https://www.malwarebytes.com/'},
    {"id": 'Microsoft.PowerToys', "name": 'Microsoft PowerToys', "category": 'Utilities & Cleaners',
     "description": 'Official Microsoft utility set: window manager, color picker, bulk renamer, and more', "foss": True,
     "url": 'https://learn.microsoft.com/en-us/windows/powertoys/'},
    {"id": 'OO-Software.ShutUp10', "name": 'O&O ShutUp10++', "category": 'Utilities & Cleaners',
     "description": 'Free one-click Windows privacy switches', "foss": False,
     "url": 'https://www.oo-software.com/en/shutup10'},
    {"id": 'Open-Shell.Open-Shell-Menu', "name": 'Open-Shell', "category": 'Utilities & Cleaners',
     "description": 'FOSS classic Start menu for Windows', "foss": True,
     "url": 'https://open-shell.github.io/Open-Shell-Menu/'},
    {"id": 'OpenVPNTechnologies.OpenVPNConnect', "name": 'OpenVPN Connect', "category": 'Utilities & Cleaners',
     "description": 'Official OpenVPN secure tunnel client', "foss": False,
     "url": 'https://openvpn.net/'},
    {"id": 'Safing.Portmaster', "name": 'Portmaster', "category": 'Utilities & Cleaners',
     "description": 'FOSS per-app firewall that blocks OS-wide telemetry connections', "foss": True,
     "url": 'https://safing.io/'},
    {"id": 'Proton.ProtonVPN', "name": 'Proton VPN', "category": 'Utilities & Cleaners',
     "description": 'Audited Swiss VPN with unlimited free data', "foss": True,
     "url": 'https://protonvpn.com/'},
    {"id": 'QL-Win.QuickLook', "name": 'QuickLook', "category": 'Utilities & Cleaners',
     "description": 'Press Spacebar to preview files in Explorer', "foss": True,
     "url": 'https://github.com/QL-Win/QuickLook'},
    {"id": 'ShareX.ShareX', "name": 'ShareX', "category": 'Utilities & Cleaners',
     "description": 'Screen capture, active-window recorder, GIF generator, and OCR utility', "foss": True,
     "url": 'https://getsharex.com/'},
    {"id": 'NirSoft.ShellMenuView', "name": 'ShellMenuView', "category": 'Utilities & Cleaners',
     "description": 'Enable or disable right-click menu items', "foss": False,
     "url": 'https://www.nirsoft.net/utils/shell_menu_view.html'},
    {"id": 'Henry++.simplewall', "name": 'Simplewall', "category": 'Utilities & Cleaners',
     "description": "Lightweight FOSS firewall that filters every app's network traffic", "foss": True,
     "url": 'https://www.henrypp.org/product/simplewall'},
    {"id": 'Ookla.Speedtest.Desktop', "name": 'Speedtest by Ookla', "category": 'Utilities & Cleaners',
     "description": 'Native Windows internet speed and ping test', "foss": False,
     "url": 'https://www.speedtest.net/apps/windows'},
    {"id": 'StefanSundin.Superf4', "name": 'SuperF4', "category": 'Utilities & Cleaners',
     "description": 'Emergency hotkey (Ctrl+Alt+F4) to kill frozen games', "foss": True,
     "url": 'https://stefansundin.github.io/superf4/'},
    {"id": 'Syncthing.Syncthing', "name": 'Syncthing', "category": 'Utilities & Cleaners',
     "description": 'FOSS continuous file sync between your PCs — no cloud, no accounts', "foss": True,
     "url": 'https://syncthing.net/'},
    {"id": 'zhongyang219.TrafficMonitor.Full', "name": 'TrafficMonitor', "category": 'Utilities & Cleaners',
     "description": 'Live network, CPU, GPU and RAM monitor', "foss": True,
     "url": 'https://github.com/zhongyang219/TrafficMonitor'},
    {"id": 'CharlesMilette.TranslucentTB', "name": 'TranslucentTB', "category": 'Utilities & Cleaners',
     "description": 'Makes Windows taskbar completely transparent or frosted glass with zero lag', "foss": True,
     "url": 'https://github.com/TranslucentTB/TranslucentTB'},
    {"id": 'xanderfrangos.twinkletray', "name": 'Twinkle Tray', "category": 'Utilities & Cleaners',
     "description": 'FOSS brightness slider for all monitors', "foss": True,
     "url": 'https://github.com/xanderfrangos/twinkle-tray'},
    {"id": 'Devolutions.UniGetUI', "name": 'UniGetUI (Winget GUI)', "category": 'Utilities & Cleaners',
     "description": 'Graphical updater for all your apps', "foss": True,
     "url": 'https://unigetui.com/'},
    {"id": 'Upscayl.Upscayl', "name": 'Upscayl', "category": 'Utilities & Cleaners',
     "description": 'Free AI upscaler: screenshots to 4K/8K', "foss": True,
     "url": 'https://www.upscayl.org/'},
    {"id": 'RamenSoftware.Windhawk', "name": 'Windhawk', "category": 'Utilities & Cleaners',
     "description": 'FOSS engine for Windows UI mods', "foss": True,
     "url": 'https://windhawk.net/'},
    {"id": 'Windscribe.Windscribe', "name": 'Windscribe VPN', "category": 'Utilities & Cleaners',
     "description": 'Free VPN with 10 GB/month and ad blocker', "foss": False,
     "url": 'https://windscribe.com/'},
    {"id": 'AntibodySoftware.WizTree', "name": 'WizTree', "category": 'Utilities & Cleaners',
     "description": 'Instant visual disk space scanner — finds huge game folders in seconds', "foss": False,
     "url": 'https://diskanalyzer.com/'},
    # H. Hardware Diagnostics & Tuning
    {"id": 'CXWorld.CapFrameX', "name": 'CapFrameX', "category": 'Hardware Diagnostics & Tuning',
     "description": 'Frametime tool to spot 1% lows and stutter', "foss": True,
     "url": 'https://www.capframex.com/'},
    {"id": '9PGZKJC81Q7J', "name": 'Cinebench 2024', "category": 'Hardware Diagnostics & Tuning',
     "description": 'Current standard CPU and GPU benchmark from Maxon (2024 release)', "foss": False,
     "url": 'https://www.maxon.net/cinebench', "fallback_url": 'https://apps.microsoft.com/detail/9PGZKJC81Q7J'},
    {"id": 'CPUID.CPU-Z', "name": 'CPU-Z', "category": 'Hardware Diagnostics & Tuning',
     "description": 'Live CPU, memory and motherboard specs', "foss": False,
     "url": 'https://www.cpuid.com/softwares/cpu-z.html'},
    {"id": 'CrystalDewWorld.CrystalDiskInfo', "name": 'CrystalDiskInfo', "category": 'Hardware Diagnostics & Tuning',
     "description": 'SSD and HDD health and temperature monitor', "foss": True,
     "url": 'https://crystalmark.info/'},
    {"id": 'CrystalDewWorld.CrystalDiskMark', "name": 'CrystalDiskMark', "category": 'Hardware Diagnostics & Tuning',
     "description": 'Standard SSD and HDD speed benchmark', "foss": True,
     "url": 'https://crystalmark.info/'},
    {"id": 'Wagnardsoft.DisplayDriverUninstaller', "name": 'Display Driver Uninstaller (DDU)', "category": 'Hardware Diagnostics & Tuning',
     "description": 'Completely removes GPU drivers and leftover registry keys in Safe Mode', "foss": True,
     "url": 'https://www.wagnardsoft.com/'},
    {"id": 'Rem0o.FanControl', "name": 'Fan Control', "category": 'Hardware Diagnostics & Tuning',
     "description": 'Control all CPU, GPU and case fan curves', "foss": False,
     "url": 'https://getfancontrol.com/'},
    {"id": 'Geeks3D.FurMark.2', "name": 'FurMark 2 GPU Stress Test', "category": 'Hardware Diagnostics & Tuning',
     "description": 'Latest GPU heat and stability stress test', "foss": False,
     "url": 'https://geeks3d.com/furmark/'},
    {"id": 'TechPowerUp.GPU-Z', "name": 'GPU-Z', "category": 'Hardware Diagnostics & Tuning',
     "description": 'Detailed graphics card information, VRAM usage, and GPU sensor monitoring', "foss": False,
     "url": 'https://www.techpowerup.com/gpuz/'},
    {"id": 'REALiX.HWiNFO', "name": 'HWiNFO64', "category": 'Hardware Diagnostics & Tuning',
     "description": 'Accurate hardware temps and voltage logging', "foss": False,
     "url": 'https://www.hwinfo.com/'},
    {"id": 'Intel.PresentMon', "name": 'Intel PresentMon', "category": 'Hardware Diagnostics & Tuning',
     "description": "FOSS frame-time and performance telemetry from Intel (CapFrameX's engine)", "foss": True,
     "url": 'https://game.intel.com/story/intel-presentmon/'},
    {"id": 'Guru3D.Afterburner', "name": 'MSI Afterburner', "category": 'Hardware Diagnostics & Tuning',
     "description": 'GPU overclocking, undervolting, and in-game FPS/temp overlay (via RTSS)', "foss": False,
     "url": 'https://www.msi.com/Landing/afterburner'},
    {"id": 'TechPowerUp.NVCleanstall', "name": 'NVCleanstall', "category": 'Hardware Diagnostics & Tuning',
     "description": 'Lean NVIDIA installer without telemetry', "foss": False,
     "url": 'https://www.techpowerup.com/nvcleanstall/'},
    {"id": 'OpenRGB.OpenRGB', "name": 'OpenRGB', "category": 'Hardware Diagnostics & Tuning',
     "description": 'FOSS RGB control, no vendor bloatware', "foss": True,
     "url": 'https://openrgb.org/'},
    # I. Disk Imaging, VMs & Torrents
    {"id": 'qBittorrent.qBittorrent', "name": 'qBittorrent', "category": 'Disk Imaging, VMs & Torrents',
     "description": 'Ad-free, open-source BitTorrent client with integrated search engine', "foss": True,
     "url": 'https://www.qbittorrent.org/'},
    {"id": 'Rufus.Rufus', "name": 'Rufus', "category": 'Disk Imaging, VMs & Torrents',
     "description": 'Fast utility to format and create bootable USB flash drives (Windows/Linux)', "foss": True,
     "url": 'https://rufus.ie/'},
    {"id": 'Ventoy.Ventoy', "name": 'Ventoy', "category": 'Disk Imaging, VMs & Torrents',
     "description": 'Boot multiple ISOs from one USB stick', "foss": True,
     "url": 'https://www.ventoy.net/'},
    {"id": 'Oracle.VirtualBox', "name": 'VirtualBox', "category": 'Disk Imaging, VMs & Torrents',
     "description": 'FOSS virtualization for Windows and Linux VMs', "foss": True,
     "url": 'https://www.virtualbox.org/'},
    # J. Local AI & GPU Model Runners
    {"id": 'Jan.Jan', "name": 'Jan AI', "category": 'Local AI & GPU Model Runners',
     "description": '100% offline, privacy-first local ChatGPT alternative powered by your GPU', "foss": True,
     "url": 'https://jan.ai/'},
    {"id": 'ElementLabs.LMStudio', "name": 'LM Studio', "category": 'Local AI & GPU Model Runners',
     "description": 'Discover and run local LLMs on your GPU', "foss": False,
     "url": 'https://lmstudio.ai/'},
    {"id": 'Ollama.Ollama', "name": 'Ollama', "category": 'Local AI & GPU Model Runners',
     "description": 'Lightweight CLI/API runtime for local AI models and background inferences', "foss": True,
     "url": 'https://ollama.com/'},
    {"id": 'SST.opencode', "name": 'OpenCode', "category": 'Local AI & GPU Model Runners',
     "description": 'Open-source AI coding agent for the terminal', "foss": True,
     "url": 'https://opencode.ai/'},
]

CATEGORY_ORDER = [
    "Driver Installers & Hardware",
    "Game Launchers, Stores & Mod Managers",
    "Gaming Tools & Emulators",
    "Web Browsers",
    "Media, Streaming & Audio",
    "Creative & Productivity",
    "Utilities & Cleaners",
    "Hardware Diagnostics & Tuning",
    "Disk Imaging, VMs & Torrents",
    "Local AI & GPU Model Runners",
]


def _validate():
    ids = [a["id"] for a in APP_CATALOG]
    assert len(ids) == len(set(ids)), "duplicate winget ids in catalog"
    for a in APP_CATALOG:
        assert a["category"] in CATEGORY_ORDER, "unknown category: " + a["category"]
        assert set(a) >= {"id", "name", "category", "description", "foss", "url"}, a["id"]
    # retired categories must stay gone
    assert "Runtimes & Dependencies" not in CATEGORY_ORDER
    assert "FOSS Games & Source Ports" not in CATEGORY_ORDER
    # A-Z within each category (user request)
    for cat in CATEGORY_ORDER:
        names = [a["name"].lower() for a in APP_CATALOG if a["category"] == cat]
        assert names == sorted(names), "category not alphabetical: " + cat
    for m in MANUAL_ONLY_APPS:
        assert m["category"] in CATEGORY_ORDER, "unknown manual category: " + m["category"]
        if "fallback_url" in m:
            assert m["fallback_url"] and m["fallback_url"] != m["url"], m["id"]


_validate()
